User login
Podiihq/devfest-registration-portal pull request #32
Opened 2019-07-01 19:05 UTC by okothkongo1

2019-07-04 12:07 UTC, TraceyOnim approved these changes

2019-07-08 05:08 UTC, jackline-kaunda requested changes
attach a screenshot showing the login process. Try to style the login page too

2019-07-08 05:09 UTC, misswayua commented
is it possible to test the login process?

2019-07-23 11:57 UTC, misswayua commented
it has been done by this user session and auth #40

2019-07-23 11:57 UTC, closed without merging