Codelab user database
Podiihq/devfest-registration-portal pull request #33
Opened 2019-07-03 11:58 UTC by TraceyOnim

2019-07-04 12:02 UTC, dennohpeter approved these changes

2019-07-08 05:11 UTC, jackline-kaunda requested changes

2019-07-08 05:11 UTC, misswayua commented on lib/devfest_registration_portal/users/user_codelab.ex
> +
is this file empty?

2019-07-08 05:12 UTC, misswayua commented
finish on creating a new codelab via the web browser, attach a screenshot and style that page

2019-07-29 12:46 UTC, TraceyOnim commented
-Codelab can now be created
![Peek 2019-07-29 15-27](https://user-images.githubusercontent.com/43263401/62049413-d9d33400-b217-11e9-88a0-571cceef3170.gif)

2019-08-06 11:47 UTC, midigofrank requested changes

2019-08-06 11:47 UTC, MidigoF commented on lib/devfest_registration_portal_web/views/challenge_view.ex
> +    categories = Codelabs.list_all_categories()
instead of calling `list_all_categories/0` from the view, i would suggest you do it from the controller then pass the data to `assigns`.

2019-08-06 11:47 UTC, MidigoF commented on lib/devfest_registration_portal_web/views/challenge_view.ex
> +    categories = Codelabs.list_all_categories()
in my opinion views should just be processing existing data, not querying for the data

2019-08-06 12:07 UTC, jackline-kaunda approved these changes

2019-08-06 12:07 UTC, merged